# Generated by Django 5.1.3 on 2024-11-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
