# Generated by Django 5.1.3 on 2024-11-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_web1', '0002_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_primary', models.CharField(max_length=100)),
                ('type_secondary', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField()),
                ('image', models.FileField(upload_to='static/assets/images')),
            ],
        ),
    ]
