# Generated by Django 5.1.3 on 2024-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web1', '0004_pokemon_gen_alter_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.FileField(upload_to='media/pokemons/'),
        ),
    ]
