# Generated by Django 5.1.3 on 2024-11-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web1', '0006_alter_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type_primary',
            field=models.CharField(choices=[('grass', 'Grass'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('ice', 'Ice'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('fighting', 'Fighting'), ('normal', 'Normal'), ('poison', 'Poison'), ('steel', 'Steel'), ('dark', 'Dark')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type_secondary',
            field=models.CharField(blank=True, choices=[('grass', 'Grass'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('ice', 'Ice'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('fighting', 'Fighting'), ('normal', 'Normal'), ('poison', 'Poison'), ('steel', 'Steel'), ('dark', 'Dark')], max_length=20, null=True),
        ),
    ]
