# Generated by Django 5.1.3 on 2024-11-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web1', '0009_remove_pokemon_author_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_primary', models.CharField(choices=[('grass', 'Grass'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('ice', 'Ice'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('fighting', 'Fighting'), ('normal', 'Normal'), ('poison', 'Poison'), ('steel', 'Steel'), ('dark', 'Dark')], max_length=20)),
                ('type_secondary', models.CharField(blank=True, choices=[('grass', 'Grass'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('ice', 'Ice'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('fighting', 'Fighting'), ('normal', 'Normal'), ('poison', 'Poison'), ('steel', 'Steel'), ('dark', 'Dark')], max_length=20, null=True)),
                ('number', models.IntegerField()),
                ('gen', models.IntegerField()),
                ('image', models.FileField(upload_to='pokemons/')),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
