# Generated by Django 5.1.3 on 2024-11-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web1', '0010_custompokemon_delete_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompokemon',
            name='gen',
        ),
        migrations.AlterField(
            model_name='custompokemon',
            name='image',
            field=models.FileField(upload_to='custom_pokemons/'),
        ),
    ]
