# Generated by Django 5.1.3 on 2024-11-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web1', '0011_remove_custompokemon_gen_alter_custompokemon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='games/')),
                ('release_date', models.DateField()),
            ],
        ),
    ]
